/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author Bilal
 */
public class Grille extends javax.swing.JFrame {

    /**
     * Creates new form Grille
     */
    public Grille() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grillePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        grillePanel.setLayout(new java.awt.GridLayout(10, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bilal\\Desktop\\CPS\\img\\tresor.png")); // NOI18N
        grillePanel.add(jLabel1);

        jLabel2.setText("jLabel2");
        grillePanel.add(jLabel2);

        jLabel3.setText("jLabel3");
        grillePanel.add(jLabel3);

        jLabel4.setText("jLabel4");
        grillePanel.add(jLabel4);

        jLabel5.setText("jLabel5");
        grillePanel.add(jLabel5);

        jLabel6.setText("jLabel6");
        grillePanel.add(jLabel6);

        jLabel7.setText("jLabel7");
        grillePanel.add(jLabel7);

        jLabel8.setText("jLabel8");
        grillePanel.add(jLabel8);

        jLabel9.setText("jLabel9");
        grillePanel.add(jLabel9);

        jLabel10.setText("jLabel10");
        grillePanel.add(jLabel10);

        jLabel11.setText("jLabel1");
        grillePanel.add(jLabel11);

        jLabel12.setText("jLabel2");
        grillePanel.add(jLabel12);

        jLabel13.setText("jLabel3");
        grillePanel.add(jLabel13);

        jLabel14.setText("jLabel4");
        grillePanel.add(jLabel14);

        jLabel15.setText("jLabel5");
        grillePanel.add(jLabel15);

        jLabel16.setText("jLabel6");
        grillePanel.add(jLabel16);

        jLabel17.setText("jLabel7");
        grillePanel.add(jLabel17);

        jLabel18.setText("jLabel8");
        grillePanel.add(jLabel18);

        jLabel19.setText("jLabel9");
        grillePanel.add(jLabel19);

        jLabel20.setText("jLabel10");
        grillePanel.add(jLabel20);

        jLabel21.setText("jLabel1");
        grillePanel.add(jLabel21);

        jLabel22.setText("jLabel2");
        grillePanel.add(jLabel22);

        jLabel23.setText("jLabel3");
        grillePanel.add(jLabel23);

        jLabel24.setText("jLabel4");
        grillePanel.add(jLabel24);

        jLabel25.setText("jLabel5");
        grillePanel.add(jLabel25);

        jLabel26.setText("jLabel6");
        grillePanel.add(jLabel26);

        jLabel27.setText("jLabel7");
        grillePanel.add(jLabel27);

        jLabel28.setText("jLabel8");
        grillePanel.add(jLabel28);

        jLabel29.setText("jLabel9");
        grillePanel.add(jLabel29);

        jLabel30.setText("jLabel10");
        grillePanel.add(jLabel30);

        jLabel31.setText("jLabel1");
        grillePanel.add(jLabel31);

        jLabel32.setText("jLabel2");
        grillePanel.add(jLabel32);

        jLabel33.setText("jLabel3");
        grillePanel.add(jLabel33);

        jLabel34.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bilal\\Desktop\\CPS\\img\\monstre.png")); // NOI18N
        grillePanel.add(jLabel34);

        jLabel35.setText("jLabel5");
        grillePanel.add(jLabel35);

        jLabel36.setText("jLabel6");
        grillePanel.add(jLabel36);

        jLabel37.setText("jLabel7");
        grillePanel.add(jLabel37);

        jLabel38.setText("jLabel8");
        grillePanel.add(jLabel38);

        jLabel39.setText("jLabel9");
        grillePanel.add(jLabel39);

        jLabel40.setText("jLabel10");
        grillePanel.add(jLabel40);

        jLabel41.setText("jLabel1");
        grillePanel.add(jLabel41);

        jLabel42.setText("jLabel2");
        grillePanel.add(jLabel42);

        jLabel43.setText("jLabel3");
        grillePanel.add(jLabel43);

        jLabel44.setText("jLabel4");
        grillePanel.add(jLabel44);

        jLabel45.setText("jLabel5");
        grillePanel.add(jLabel45);

        jLabel46.setText("jLabel6");
        grillePanel.add(jLabel46);

        jLabel47.setText("jLabel7");
        grillePanel.add(jLabel47);

        jLabel48.setText("jLabel8");
        grillePanel.add(jLabel48);

        jLabel49.setText("jLabel9");
        grillePanel.add(jLabel49);

        jLabel50.setText("jLabel10");
        grillePanel.add(jLabel50);

        jLabel51.setText("jLabel1");
        grillePanel.add(jLabel51);

        jLabel52.setText("jLabel2");
        grillePanel.add(jLabel52);

        jLabel53.setText("jLabel3");
        grillePanel.add(jLabel53);

        jLabel54.setText("jLabel4");
        grillePanel.add(jLabel54);

        jLabel55.setText("jLabel5");
        grillePanel.add(jLabel55);

        jLabel56.setText("jLabel6");
        grillePanel.add(jLabel56);

        jLabel57.setText("jLabel7");
        grillePanel.add(jLabel57);

        jLabel58.setText("jLabel8");
        grillePanel.add(jLabel58);

        jLabel59.setText("jLabel9");
        grillePanel.add(jLabel59);

        jLabel60.setText("jLabel10");
        grillePanel.add(jLabel60);

        jLabel61.setText("jLabel1");
        grillePanel.add(jLabel61);

        jLabel62.setText("jLabel2");
        grillePanel.add(jLabel62);

        jLabel63.setText("jLabel3");
        grillePanel.add(jLabel63);

        jLabel64.setText("jLabel4");
        grillePanel.add(jLabel64);

        jLabel65.setText("jLabel5");
        grillePanel.add(jLabel65);

        jLabel66.setText("jLabel6");
        grillePanel.add(jLabel66);

        jLabel67.setText("jLabel7");
        grillePanel.add(jLabel67);

        jLabel68.setText("jLabel8");
        grillePanel.add(jLabel68);

        jLabel69.setText("jLabel9");
        grillePanel.add(jLabel69);

        jLabel70.setText("jLabel10");
        grillePanel.add(jLabel70);

        jLabel71.setText("jLabel1");
        grillePanel.add(jLabel71);

        jLabel72.setText("jLabel2");
        grillePanel.add(jLabel72);

        jLabel73.setText("jLabel3");
        grillePanel.add(jLabel73);

        jLabel74.setText("jLabel4");
        grillePanel.add(jLabel74);

        jLabel75.setText("jLabel5");
        grillePanel.add(jLabel75);

        jLabel76.setText("jLabel6");
        grillePanel.add(jLabel76);

        jLabel77.setText("jLabel7");
        grillePanel.add(jLabel77);

        jLabel78.setText("jLabel8");
        grillePanel.add(jLabel78);

        jLabel79.setText("jLabel9");
        grillePanel.add(jLabel79);

        jLabel80.setText("jLabel10");
        grillePanel.add(jLabel80);

        jLabel81.setText("jLabel1");
        grillePanel.add(jLabel81);

        jLabel82.setText("jLabel2");
        grillePanel.add(jLabel82);

        jLabel83.setText("jLabel3");
        grillePanel.add(jLabel83);

        jLabel84.setText("jLabel4");
        grillePanel.add(jLabel84);

        jLabel85.setText("jLabel5");
        grillePanel.add(jLabel85);

        jLabel86.setText("jLabel6");
        grillePanel.add(jLabel86);

        jLabel87.setText("jLabel7");
        grillePanel.add(jLabel87);

        jLabel88.setText("jLabel8");
        grillePanel.add(jLabel88);

        jLabel89.setText("jLabel9");
        grillePanel.add(jLabel89);

        jLabel90.setText("jLabel10");
        grillePanel.add(jLabel90);

        jLabel91.setText("jLabel1");
        grillePanel.add(jLabel91);

        jLabel92.setText("jLabel2");
        grillePanel.add(jLabel92);

        jLabel93.setText("jLabel3");
        grillePanel.add(jLabel93);

        jLabel94.setText("jLabel4");
        grillePanel.add(jLabel94);

        jLabel95.setText("jLabel5");
        grillePanel.add(jLabel95);

        jLabel96.setText("jLabel6");
        grillePanel.add(jLabel96);

        jLabel97.setText("jLabel7");
        grillePanel.add(jLabel97);

        jLabel98.setText("jLabel8");
        grillePanel.add(jLabel98);

        jLabel99.setText("jLabel9");
        grillePanel.add(jLabel99);

        jLabel100.setText("jLabel10");
        grillePanel.add(jLabel100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(grillePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(grillePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grille.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grille.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grille.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grille.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grille().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel grillePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    // End of variables declaration//GEN-END:variables
}
