/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import components.Environment;
import components.Player;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import services.Dir;

/**
 *
 * @author Bilal
 */
public class Partie extends javax.swing.JFrame {

    /**
     * Creates new form Partie
     */
    Player player;
    Environment env;
    private JLabel [][] jLabelMatrice = new JLabel[3][5];
    public Partie() {
        initComponents();
        jLabelMatrice [0][0] = jLabel00;
        jLabelMatrice [0][1] = jLabel01;
        jLabelMatrice [0][2] = jLabel02;
        jLabelMatrice [0][3] = jLabel03;
        jLabelMatrice [0][4] = jLabel04;
        jLabelMatrice [1][0] = jLabel10;
        jLabelMatrice [1][1] = jLabel11;
        jLabelMatrice [1][2] = jLabel12;
        jLabelMatrice [1][3] = jLabel13;
        jLabelMatrice [1][4] = jLabel14;
        jLabelMatrice [2][0] = jLabel20;
        jLabelMatrice [2][1] = jLabel21;
        jLabelMatrice [2][2] = jLabel22;
        jLabelMatrice [2][3] = jLabel23;
        jLabelMatrice [2][4] = jLabel24;
        
    }

    public void setPlayer(Player player) {
        this.player = player;
    }

    public void setEnv(Environment env) {
        this.env = env;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vuCourantPanel = new javax.swing.JPanel();
        gauchePanel = new javax.swing.JPanel();
        jLabel04 = new javax.swing.JLabel();
        jLabel03 = new javax.swing.JLabel();
        jLabel02 = new javax.swing.JLabel();
        jLabel01 = new javax.swing.JLabel();
        jLabel00 = new javax.swing.JLabel();
        mileuPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        droitePanel = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        upButton = new javax.swing.JButton();
        leftButton = new javax.swing.JButton();
        rightButton = new javax.swing.JButton();
        downButton3 = new javax.swing.JButton();
        turnRightButton = new javax.swing.JButton();
        turnLeftButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        vuCourantPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        vuCourantPanel.setLayout(new java.awt.GridLayout(1, 3));

        gauchePanel.setLayout(new java.awt.GridLayout(5, 1));
        gauchePanel.add(jLabel04);
        gauchePanel.add(jLabel03);
        gauchePanel.add(jLabel02);
        gauchePanel.add(jLabel01);
        gauchePanel.add(jLabel00);

        vuCourantPanel.add(gauchePanel);

        mileuPanel.setLayout(new java.awt.GridLayout(5, 1));
        mileuPanel.add(jLabel14);
        mileuPanel.add(jLabel13);
        mileuPanel.add(jLabel12);
        mileuPanel.add(jLabel11);
        mileuPanel.add(jLabel10);

        vuCourantPanel.add(mileuPanel);

        droitePanel.setLayout(new java.awt.GridLayout(5, 1));
        droitePanel.add(jLabel24);
        droitePanel.add(jLabel23);
        droitePanel.add(jLabel22);
        droitePanel.add(jLabel21);

        jLabel20.setBackground(new java.awt.Color(102, 102, 102));
        droitePanel.add(jLabel20);

        vuCourantPanel.add(droitePanel);

        upButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bilal\\Desktop\\CPS\\img\\up.png")); // NOI18N
        upButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButtonActionPerformed(evt);
            }
        });

        leftButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bilal\\Desktop\\CPS\\img\\left.png")); // NOI18N
        leftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftButtonActionPerformed(evt);
            }
        });

        rightButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bilal\\Desktop\\CPS\\img\\right.png")); // NOI18N
        rightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightButtonActionPerformed(evt);
            }
        });

        downButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bilal\\Desktop\\CPS\\img\\down.png")); // NOI18N
        downButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downButton3ActionPerformed(evt);
            }
        });

        turnRightButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bilal\\Desktop\\CPS\\img\\turnRight.png")); // NOI18N
        turnRightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnRightButtonActionPerformed(evt);
            }
        });

        turnLeftButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bilal\\Desktop\\CPS\\img\\turnLeft.png")); // NOI18N
        turnLeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnLeftButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(turnLeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(turnRightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(leftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(vuCourantPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(downButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(vuCourantPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(turnRightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(turnLeftButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rightButton)
                            .addComponent(leftButton))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(upButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(downButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void upButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButtonActionPerformed
        try {
            player.forward();
          //  System.out.println(player.getCol()+" "+player.getRow());
            setVueCourante(player.vueCourante());
        } catch (Exception ex) {
            Logger.getLogger(Partie.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_upButtonActionPerformed

    private void leftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftButtonActionPerformed
         try {
            player.strafeL();
          //  System.out.println(player.getCol()+" "+player.getRow());
            setVueCourante(player.vueCourante());
        } catch (Exception ex) {
            Logger.getLogger(Partie.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_leftButtonActionPerformed

    private void rightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightButtonActionPerformed
         try {
            player.strafeR();
          //  System.out.println(player.getCol()+" "+player.getRow());
            setVueCourante(player.vueCourante());
        } catch (Exception ex) {
            Logger.getLogger(Partie.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rightButtonActionPerformed

    private void downButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downButton3ActionPerformed
         try {
            player.backward();
            System.out.println(player.getCol()+" "+player.getRow());
          //  setVueCourante(player.vueCourante());
        } catch (Exception ex) {
            Logger.getLogger(Partie.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_downButton3ActionPerformed

    private void turnRightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnRightButtonActionPerformed
       try {
           
            player.turnL();
           // System.out.println(player.getCol()+" "+player.getRow());
            setVueCourante(player.vueCourante());
        } catch (Exception ex) {
            Logger.getLogger(Partie.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_turnRightButtonActionPerformed

    private void turnLeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnLeftButtonActionPerformed
        try {
            player.turnR();
            System.out.println(player.getCol()+" "+player.getRow());
            setVueCourante(player.vueCourante());
        } catch (Exception ex) {
            Logger.getLogger(Partie.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_turnLeftButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Partie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Partie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Partie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Partie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Partie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton downButton3;
    private javax.swing.JPanel droitePanel;
    private javax.swing.JPanel gauchePanel;
    private javax.swing.JLabel jLabel00;
    private javax.swing.JLabel jLabel01;
    private javax.swing.JLabel jLabel02;
    private javax.swing.JLabel jLabel03;
    private javax.swing.JLabel jLabel04;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JButton leftButton;
    private javax.swing.JPanel mileuPanel;
    private javax.swing.JButton rightButton;
    private javax.swing.JButton turnLeftButton;
    private javax.swing.JButton turnRightButton;
    private javax.swing.JButton upButton;
    private javax.swing.JPanel vuCourantPanel;
    // End of variables declaration//GEN-END:variables

   
    
    
public void setVueCourante (String [][] matrice){
    for (int i =0; i<3 ; i++){
        for (int j =0; j<5; j++){
            jLabelMatrice[i][j].setIcon(new javax.swing.ImageIcon("C:\\Users\\Bilal\\Desktop\\CPS\\img\\"+matrice[i][j]+".png")); // NOI18N
            jLabelMatrice[i][j].setText(matrice[i][j]);
        }
    }
}


}
